apiVersion: compute.do.crossplane.io/v1alpha1
kind: Droplet
metadata:
  name: cod-r-crossplane-droplet
  annotations:
    crossplane.io/external-name: cod-r-crossplane-droplet
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  forProvider:
    region: fra1
    size: s-1vcpu-1gb
    image: ubuntu-20-04-x64
  providerConfigRef:
    name: do-config
